"""Acceptance test: document-decomposition -> evidence-extraction -> matching.

A DOCUMENT IS NOT AN ACTIVITY.  A Daily Construction Report is a container of
many heterogeneous observations; only eligible ones are resolved against
schedule activities.  This drives the real pipeline (no HTTP, no reasoning
provider, no Horizun) over the Project 218 regression fixture and checks the
20 documented pass conditions.

Fixtures (generated by tools/make_project_218_fixture.py):
  sample_data/Project_218_P6_Style_Activities.csv
  sample_data/Daily_Construction_Report_218_TEXT_EXTRACTABLE.pdf

Usage:  .venv\\Scripts\\python.exe tools\\dcr_pipeline_acceptance_test.py
"""
from __future__ import annotations

import csv
import os
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
_TMP = tempfile.TemporaryDirectory(prefix="veda_dcr_accept_")
os.environ["VEDA_DATA_DIR"] = str(Path(_TMP.name) / "data")
os.environ["VEDA_OCR"] = "0"

from veda import db                                             # noqa: E402
from veda.api import routes                                     # noqa: E402
from veda.pipeline import deterministic, documents, extract, ingest, linking  # noqa: E402

SAMPLES = ROOT / "sample_data"
CSV = SAMPLES / "Project_218_P6_Style_Activities.csv"
PDF = SAMPLES / "Daily_Construction_Report_218_TEXT_EXTRACTABLE.pdf"

PASS: list[str] = []
FAIL: list[str] = []


def check(label: str, ok: bool, detail: str = "") -> bool:
    (PASS if ok else FAIL).append(label)
    print(("  [PASS] " if ok else "  [FAIL] ") + label + (("  -> " + detail) if detail else ""))
    return ok


def load_schedule(pid: str) -> dict:
    """Insert the authoritative schedule exactly as the CSV fixture states it."""
    with open(CSV, encoding="utf-8-sig", newline="") as fh:
        rows = list(csv.DictReader(fh))
    snap = db.insert("schedule_snapshots", {
        "project_id": pid, "revision": 1, "is_current": 1,
        "project_name": "Project 218", "status_date": "2017-10-02",
        "data_date": "2017-10-02", "planned_start": "2017-08-14",
        "planned_finish": "2017-10-20", "task_count": len(rows),
    })
    uid_by_id: dict[str, int] = {}
    for i, r in enumerate(rows, start=1):
        uid_by_id[r["Activity ID"]] = i
        db.insert("activities", {
            "project_id": pid, "snapshot_id": snap, "uid": i,
            "display_id": r["Activity ID"], "name": r["Activity Name"],
            "wbs": r["WBS"], "wbs_name": r["WBS"].split(".")[-1], "wbs_path": r["WBS"],
            "is_summary": 0, "status": r["Status"],
            "start": r["Start"], "finish": r["Finish"],
            "baseline_start": r["Baseline Start"], "baseline_finish": r["Baseline Finish"],
            "percent_complete": float(r["% Complete"] or 0),
            "duration_days": float(r["Duration"] or 0), "provenance": "MCP_FACT",
        })
    return uid_by_id


def main() -> None:
    db.init_db()
    pid = db.insert("projects", {"name": "Project 218 acceptance", "status": "active",
                                 "updated_at": db.now()})
    uid = load_schedule(pid)

    # ---- ingest the DCR exactly as the website would --------------------
    data = PDF.read_bytes()
    stored = ingest.store_upload(pid, PDF.name, data, "application/pdf")
    f = db.q1("SELECT * FROM files WHERE id=?", [stored["id"]])

    rows = extract.extract_evidence(pid, f, None)
    for r in rows:
        db.insert("evidence", extract.enrich_evidence_record(r))

    ev_all = db.q("SELECT * FROM evidence WHERE project_id=?", [pid])
    by_type: dict[str, list] = {}
    for e in ev_all:
        by_type.setdefault(e.get("observation_type") or "?", []).append(e)
    activity_obs = by_type.get("activity_progress", [])
    issue_obs = by_type.get("issue", [])

    print("\n== STAGE: decomposition ==")
    check("1. PDF produced more than one atomic observation", len(ev_all) > 1,
          f"{len(ev_all)} observations")
    whole_page = [e for e in ev_all if "WORK PROGRESS" in (e.get("description") or "").upper()
                  and "MANPOWER" in (e.get("description") or "").upper()]
    check("2. entire page text is NOT one activity-match record", not whole_page)
    check("3. at least six work-progress observations detected", len(activity_obs) >= 6,
          f"{len(activity_obs)} activity-progress observations")

    slab = next((e for e in activity_obs
                 if e["description"].lower().startswith("formworks first floor slab")), None)
    rv = db.jloads((slab or {}).get("raw_values_json"), {}) or {}
    check("5. first-floor slab formwork quantities extracted",
          bool(slab) and rv.get("total_qty") == 2000 and rv.get("planned_today") == 500
          and rv.get("achieved_today") == 300 and rv.get("plan_next_day") == 200
          and rv.get("cumulative_qty") == 1200 and rv.get("percent_complete") == 60
          and slab.get("observed_progress") == 60,
          str(rv))
    zones = {e.get("location") for e in activity_obs}
    check("6. zone values survive extraction",
          {"Zone 1", "Zone 2", "Zone 3"}.issubset(zones), str(sorted(z for z in zones if z)))

    drop = next((e for e in activity_obs if "drop beams" in e["description"].lower()), None)
    drv = db.jloads((drop or {}).get("raw_values_json"), {}) or {}
    check("13. blank progress cells stay null / unreported",
          bool(drop) and drv.get("percent_complete") is None
          and drop.get("observed_progress") is None
          and all(drv.get(k) is None for k in ("total_qty", "planned_today", "achieved_today")),
          str(drv))

    check("7. manpower observations are separate from activity observations",
          len(by_type.get("manpower", [])) >= 4)
    welder = next((e for e in by_type.get("manpower", [])
                   if "welder" in (e.get("description") or "").lower()), None)
    welding_contamination = [e for e in activity_obs
                             if (e.get("discipline") or "").lower() == "welding"
                             or (e.get("action_type") or "").lower() == "welding"
                             or (e.get("event_type") or "").lower() == "welding"]
    check("8. 'Welder' does not produce a global 'Welding' classification",
          welder is not None and welder.get("observation_type") == "manpower"
          and not welding_contamination,
          f"welding-tagged activity obs: {len(welding_contamination)}")

    # ---- date handling ------------------------------------------------
    print("\n== STAGE: date handling ==")
    meta = next((e for e in by_type.get("report_metadata", [])), None)
    di = db.jloads((meta or {}).get("date_interpretations_json"), {}) or {}
    isos = {i["iso"] for i in di.get("interpretations", [])}
    check("11. raw ambiguous date '10.03.2017' is preserved",
          (meta or {}).get("raw_date") == "10.03.2017" and di.get("raw") == "10.03.2017")
    check("12. date normalization does not silently assume DD.MM.YYYY",
          di.get("ambiguous") is True and {"2017-10-03", "2017-03-10"} <= isos
          and di.get("normalized") == "2017-10-03" and di.get("reason"),
          f"{di.get('normalized')} ({di.get('date_format_interpretation')}); reason={di.get('reason')}")

    # ---- placeholder guard -----------------------------------------
    print("\n== STAGE: extraction guard ==")
    import pymupdf
    scan = pymupdf.open()
    p = scan.new_page(width=300, height=300)
    p.draw_rect(pymupdf.Rect(20, 20, 280, 280), color=(0, 0, 0))
    scan_path = Path(_TMP.name) / "image_only.pdf"
    scan.save(str(scan_path))
    scan.close()
    scan_stored = ingest.store_upload(pid, "image_only.pdf", scan_path.read_bytes(),
                                      "application/pdf")
    sf = db.q1("SELECT * FROM files WHERE id=?", [scan_stored["id"]])
    raised = False
    try:
        extract.extract_evidence(pid, sf, None)
    except documents.ExtractionRequired as exc:
        raised = True
        reason = exc.reason
    check("14. no activity matching occurs on extraction placeholders",
          raised, "ExtractionRequired: " + (reason if raised else "not raised"))

    # ---- idempotency ---------------------------------------------------
    print("\n== STAGE: idempotency ==")
    redup = ingest.store_upload(pid, PDF.name, data, "application/pdf")
    keys_before = sorted(e["observation_key"] for e in ev_all if e.get("observation_key"))
    rows2 = extract.extract_evidence(pid, f, None)
    keys_after = sorted(r.get("observation_key") for r in rows2 if r.get("observation_key"))
    check("15. re-upload does not create duplicate evidence",
          redup.get("skipped") is True and keys_before == keys_after
          and len(keys_after) == len(set(keys_after)),
          f"duplicate_of={redup.get('duplicate_of')}, {len(keys_after)} stable keys")

    # ---- source vs observation counts -------------------------------
    print("\n== STAGE: dashboard semantics ==")
    fctx = routes._field_evidence_context(pid)
    obs_sources = int(db.q1("SELECT COUNT(DISTINCT file_id) c FROM evidence "
                            "WHERE project_id=? AND file_id IS NOT NULL", [pid])["c"])
    check("16. the DCR is one source while its observation count is > 1",
          obs_sources == 1 and fctx["evidence_observation_count"] > 1
          and fctx["activity_observation_count"] == len(activity_obs),
          f"the DCR yielded {fctx['evidence_observation_count']} observations from 1 source "
          f"(activity={fctx['activity_observation_count']}, issue={fctx['issue_observation_count']}, "
          f"context={fctx['context_observation_count']}); "
          f"the image-only PDF is a separate source flagged extraction_required")

    # ---- activity matching -----------------------------------------
    print("\n== STAGE: activity resolution (per observation) ==")
    stats = linking.link_evidence(pid, raise_reviews=True)
    expected = {
        "formworks first floor slab": "P218-STR-Z3-060",
        "formworks drop beams -1st flr": "P218-STR-Z3-050",
        "post tension duct installation-1st flr": "P218-PT-Z3-070",
        "plumbing sleeve installation-1st flr": "P218-MEP-Z3-080",
        "scaffolding erection for first flr slab": "P218-STR-Z2-040",
        "formworks column - grnd floor": "P218-STR-Z1-010",
    }
    resolved_ok = 0
    high_conf = 0
    for e in db.q("SELECT * FROM evidence WHERE project_id=? AND observation_type='activity_progress'", [pid]):
        want_disp = expected.get(e["description"].lower())
        link = db.q1("SELECT * FROM evidence_links WHERE evidence_id=? AND is_candidate=0 "
                     "ORDER BY created_at DESC LIMIT 1", [e["id"]])
        got_uid = (link or {}).get("recommended_uid") or (link or {}).get("activity_uid")
        ok = want_disp is not None and got_uid == uid.get(want_disp)
        resolved_ok += ok
        conf = float((link or {}).get("confidence") or 0)
        if ok and conf >= 0.9:
            high_conf += 1
        print(f"     {e['description'][:44]:44s} -> uid {got_uid} "
              f"({'OK ' if ok else 'XX '}want {want_disp}) conf={conf:.2f} state={e.get('state')}")
    check("4. the six schedule mappings are correctly resolved", resolved_ok == 6,
          f"{resolved_ok}/6")
    check("4b. exact identity matches carry HIGH identity confidence (>=0.9)",
          high_conf == 6, f"{high_conf}/6 >= 0.90")

    # ---- human review is per observation, not per page ----------------
    print("\n== STAGE: human review shape ==")
    clar = db.q("SELECT * FROM reviews WHERE project_id=? AND kind='clarification' "
                "AND status='open'", [pid])
    page_level = []
    for rv_row in clar:
        ids = db.jloads(rv_row.get("affected_ids_json"), []) or []
        kinds = {db.q1("SELECT observation_type FROM evidence WHERE id=?", [i])["observation_type"]
                 for i in ids if db.q1("SELECT observation_type FROM evidence WHERE id=?", [i])}
        if len(kinds) > 1:
            page_level.append(rv_row["id"])
    check("17. human review is per ambiguous observation, not per whole page",
          not page_level and all(
              len(db.jloads(r.get("affected_ids_json"), []) or []) <= len(activity_obs)
              for r in clar),
          f"{len(clar)} clarification review(s); heterogeneous={len(page_level)}")

    # ---- issues extracted independently -----------------------------
    print("\n== STAGE: issue extraction ==")
    result = deterministic.analyse(pid)
    dcr_issues = [i for i in result.issues if i.ref and i.ref.startswith("F06")]
    check("9. two critical issues are independently extracted", len(dcr_issues) == 2,
          f"{[i.ref for i in dcr_issues]}")
    z3_130 = uid.get("P218-STR-Z3-130")
    both_resolved = all(z3_130 in (i.activity_uids or []) for i in dcr_issues)
    check("10. both issues resolve affected work to P218-STR-Z3-130", both_resolved,
          f"{[(i.ref, i.activity_uids) for i in dcr_issues]}")
    check("9b. issues are NOT ordinary activity-progress records",
          all(e.get("observation_type") == "issue" for e in issue_obs)
          and all(db.q1("SELECT state FROM evidence WHERE id=?", [e["id"]])["state"] == "issue"
                  for e in issue_obs)
          and not any(db.q("SELECT id FROM evidence_links WHERE evidence_id=?", [e["id"]])
                      for e in issue_obs))

    # ---- schedule facts stay separate --------------------------------
    print("\n== STAGE: governance separation ==")
    off = db.q1("SELECT percent_complete FROM activities WHERE project_id=? AND uid=?",
                [pid, uid["P218-STR-Z3-060"]])
    obsprog = db.q1("SELECT observed_percent, official_percent FROM observed_progress "
                    "WHERE project_id=? AND activity_uid=?", [pid, uid["P218-STR-Z3-060"]])
    check("18. field observation is separate from official schedule value",
          off["percent_complete"] == 45.0 and obsprog is not None
          and obsprog["observed_percent"] == 60.0,
          f"official={off['percent_complete']} observed={(obsprog or {}).get('observed_percent')}")
    props = db.q("SELECT * FROM proposals WHERE project_id=?", [pid])
    check("19. no official schedule change occurs without governance/approval",
          all(p.get("approval_state") in (None, "pending") for p in props)
          and all(p.get("execution_state") in (None, "not_executed") for p in props),
          f"{len(props)} proposal(s), all pending")

    # ---- provenance -------------------------------------------------
    print("\n== STAGE: provenance ==")
    traceable = all(
        e.get("source_file") and e.get("locator") and e.get("section") is not None
        and e.get("raw_text") and e.get("observation_key")
        and str(e.get("locator")).startswith("page ")
        for e in ev_all if e.get("observation_type") != "general")
    check("20. every observation is traceable to page / section / row / raw text",
          traceable)

    print("\n" + "=" * 68)
    print(f"  {len(PASS)} passed, {len(FAIL)} failed")
    if FAIL:
        for x in FAIL:
            print("   FAIL:", x)
        sys.exit(1)
    print("  DCR pipeline acceptance test PASSED")


if __name__ == "__main__":
    main()
